### ISSUE TITLE
"Öffentlich" Flag lässt sich beliebig bearbeiten - keine Fehlermeldung

### ISSUE THREAD

**Issue by geruetzel** [WolfgaungBeer/mailTemplates#2]
Das Bearbeiten vom Standardwert "true" im Flag, ob ein Template öffentlich ist, oder nicht, lässt beliebige Texteingabe zu, ohne Fehlerausgabe. Vorschlag: Dropdownmenü für 1x true, 1x false.

**Comment by WolfgaungBeer** [comment]
Dropdownmenü wurde implementiert, es gibt nur noch die Möglichkeiten: "true" und "false" zur Auswahl
